server:
  port: 8082

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:h2:file:./data/patient_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: ${JWT_SECRET:Y2hhbmdlLW1lLWxvY2FsLWRldi1zZWNyZXQtaG9zcGl0YWwtbWFuYWdlbWVudC1zeXN0ZW0tMjAyNg==}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.hospital: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/patient_db
    username: ${POSTGRES_USER:hms}
    password: ${POSTGRES_PASSWORD:hms_pw}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
